### ISSUE TITLE
Trying to use Auth0 but I get 401 Unautorized 

### ISSUE THREAD

**Issue by rajaraodv** [perkinsjr/nextauth-examples#1]
Hi there,
Thanks for the video. I followed all the steps but for some reason when I click on Auth0 button, instead of showing the Auth0's login page, it shows the following error.  Wondering what exact callback URL did you set up? I set it up as http://localhost:3000/api/auth/callback/auth0. Not sure what I might be missing

https://next-auth.js.org/errors#oauth_get_access_token_error
[next-auth][error][oauth_get_access_token_error] [
  {
    statusCode: 401,
    data: '{"error":"access_denied","error_description":"Unauthorized"}'
  },
  undefined,
  'auth0',
  'qnac2K0VwP1Rv8LN'
] 
https://next-auth.js.org/errors#oauth_get_access_token_error
[next-auth][error][callback_oauth_error] {
  statusCode: 401,
  data: '{"error":"access_denied","error_description":"Unauthorized"}'
} 
https://next-auth.js.org/errors#callback_oauth_error

**Comment by perkinsjr** [comment]
This issue is returned from Auth0 usually when you are using incorrect credentials for them or you have not authorized the application to be used. 


The callback should be /api/auth/callback/[provider] so that is not an issue.  You need to look at your auth0 configuration + make sure your .env has the correct details.

**Comment by rajaraodv** [comment]
@perkinsjr  I think Auth0 needs more things now. Not sure how to set them up using nextAuth. https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md#basic-setup

AUTH0_SECRET='LONG_RANDOM_VALUE'
AUTH0_BASE_URL='http://localhost:3000'
AUTH0_ISSUER_BASE_URL='https://your-tenant.auth0.com'
AUTH0_CLIENT_ID='CLIENT_ID'
AUTH0_CLIENT_SECRET='CLIENT_SECRET'

I could easily login using nextjs-auth0 library without any changes.

**Comment by perkinsjr** [comment]
They only require the following

import Providers from `next-auth/providers`
...
providers: [
  Providers.Auth0({
    clientId: process.env.AUTH0_CLIENT_ID,
    clientSecret: process.env.AUTH0_CLIENT_SECRET,
    domain: process.env.AUTH0_DOMAIN
  })
]
...

this is not an issue of the tutorial, at the time of the recording everything works as expected. 

If you want to discuss future please move to discord or email.
